name: Run xmap-stats.py Script

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  execute_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Choose the Python version your script is compatible with

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies from requirements.txt
        # If you have a setup.py for your package, use pip to install the package itself
        # pip install .

    - name: Run Script
      run: python -m your_package.xmap-stats  # Run your script as a module
